from __future__ import annotations

from typing import Any


def _product(
    *,
    sku: str,
    slug: str,
    name: str,
    category: str,
    product_type: str,
    collection: str,
    price_cents: int,
    image_url: str,
    sizes: list[str],
    colors: list[str],
    in_stock: bool,
    requires_size: bool = True,
    shipping_cents: int = 1000,
    old_price_cents: int | None = None,
    stock_total: int | None = None,
) -> dict[str, Any]:
    quantity = stock_total if stock_total is not None else (24 if in_stock else 0)
    return {
        "sku": sku,
        "slug": slug,
        "name": name,
        "description": f"{category}{product_type}，归属“{collection}”系列，可在后台统一维护价格、库存与图集。",
        "category": category,
        "product_type": product_type,
        "collection": collection,
        "price_cents": price_cents,
        "old_price_cents": old_price_cents,
        "image_url": image_url,
        "sizes": sizes,
        "colors": colors,
        "requires_size": requires_size,
        "shipping_cents": shipping_cents,
        "in_stock": in_stock,
        "stock_total": quantity,
    }


CATALOG_PRODUCTS: list[dict[str, Any]] = [
    _product(
        sku="MEN-001",
        slug="men-moon-cycle-tshirt",
        name="月相鹿影宽松T恤",
        category="男装",
        product_type="T恤",
        collection="限量系列",
        price_cents=10999,
        old_price_cents=13999,
        image_url="/catalogue-products/men-moon-cycle-tshirt.png",
        sizes=["S", "M", "L", "XL"],
        colors=["#808080"],
        in_stock=True,
    ),
    _product(
        sku="MEN-002",
        slug="men-knit-pullover-loose",
        name="宽松七分袖针织衫",
        category="男装",
        product_type="卫衣",
        collection="夏季新品",
        price_cents=11999,
        image_url="/catalogue-products/men-knit-pullover.png",
        sizes=["S", "M", "L"],
        colors=["#89541f", "#dec78f"],
        in_stock=True,
    ),
    _product(
        sku="MEN-003",
        slug="men-moon-lake-tshirt",
        name="月下山林宽松T恤",
        category="男装",
        product_type="T恤",
        collection="限量系列",
        price_cents=10999,
        image_url="/catalogue-products/men-moon-lake-tshirt.png",
        sizes=["M", "L", "XL"],
        colors=["#0b7fb8"],
        in_stock=False,
    ),
    _product(
        sku="MEN-004",
        slug="men-black-tank",
        name="黑色运动背心",
        category="男装",
        product_type="背心",
        collection="夏季新品",
        price_cents=6999,
        image_url="/catalogue-products/men-tank.png",
        sizes=["S", "M"],
        colors=["#000000"],
        in_stock=True,
    ),
    _product(
        sku="MEN-005",
        slug="men-formal-shirt",
        name="高级正装衬衫",
        category="男装",
        product_type="正装衬衫",
        collection="基础通勤",
        price_cents=11999,
        image_url="/catalogue-products/men-formal-shirt.png",
        sizes=["M", "L", "XL", "XXL"],
        colors=["#ffffff"],
        in_stock=False,
    ),
    _product(
        sku="MEN-006",
        slug="men-striped-shirt",
        name="条纹正装衬衫",
        category="男装",
        product_type="正装衬衫",
        collection="限量系列",
        price_cents=7999,
        image_url="/catalogue-products/men-striped-shirt.png",
        sizes=["S", "M", "L", "XL"],
        colors=["#ffffff", "#0b7fb8"],
        in_stock=True,
    ),
    _product(
        sku="MEN-007",
        slug="men-oxford-shirt",
        name="牛津衬衫",
        category="男装",
        product_type="正装衬衫",
        collection="基础通勤",
        price_cents=7999,
        image_url="/catalogue-products/men-oxford-shirt.png",
        sizes=["S", "M", "L", "XL"],
        colors=["#ffffff", "#0b7fb8"],
        in_stock=True,
    ),
    _product(
        sku="MEN-008",
        slug="men-moon-deer-tshirt",
        name="满月鹿影印花T恤",
        category="男装",
        product_type="T恤",
        collection="限量系列",
        price_cents=10999,
        image_url="/catalogue-products/men-moon-deer-tshirt.png",
        sizes=["S", "M", "L", "XL"],
        colors=["#000000"],
        in_stock=True,
    ),
    _product(
        sku="MEN-009",
        slug="men-light-gray-sweatshirt",
        name="浅灰休闲卫衣",
        category="男装",
        product_type="卫衣",
        collection="夏季新品",
        price_cents=12999,
        image_url="/catalogue-products/men-knit-pullover.png",
        sizes=["M", "L", "XL"],
        colors=["#808080"],
        in_stock=True,
    ),
    _product(
        sku="WOMEN-001",
        slug="women-camellia-dress",
        name="山茶花连衣裙",
        category="女装",
        product_type="连衣裙",
        collection="春夏精选",
        price_cents=12999,
        old_price_cents=15999,
        image_url="/catalogue-products/women-dress.png",
        sizes=["S", "M"],
        colors=["#dec78f", "#ffffff"],
        in_stock=True,
    ),
    _product(
        sku="WOMEN-002",
        slug="women-cloud-cardigan",
        name="云感针织开衫",
        category="女装",
        product_type="针织衫",
        collection="轻通勤",
        price_cents=13999,
        image_url="/catalogue-products/women-cardigan.png",
        sizes=["S", "M", "L", "XL"],
        colors=["#dec78f", "#89541f"],
        in_stock=True,
    ),
    _product(
        sku="WOMEN-003",
        slug="women-commute-skirt",
        name="高腰通勤半身裙",
        category="女装",
        product_type="半身裙",
        collection="轻通勤",
        price_cents=9999,
        image_url="/catalogue-products/women-skirt.png",
        sizes=["S", "M", "L"],
        colors=["#dec78f", "#808080"],
        in_stock=False,
    ),
    _product(
        sku="WOMEN-004",
        slug="women-cotton-blouse",
        name="清爽棉质衬衫",
        category="女装",
        product_type="衬衫",
        collection="度假系列",
        price_cents=8999,
        image_url="/catalogue-products/women-blouse.png",
        sizes=["S", "M", "L", "XL"],
        colors=["#ffffff", "#0b7fb8"],
        in_stock=True,
    ),
    _product(
        sku="WOMEN-005",
        slug="women-nature-growth-tshirt",
        name="自然生长宽松T恤",
        category="女装",
        product_type="T恤",
        collection="春夏精选",
        price_cents=9999,
        image_url="/catalogue-products/women-nature-growth-tshirt.png",
        sizes=["S", "M", "L", "XL"],
        colors=["#dec78f"],
        in_stock=True,
    ),
    _product(
        sku="WOMEN-006",
        slug="women-bamboo-moon-tshirt",
        name="竹月鹿影宽松T恤",
        category="女装",
        product_type="T恤",
        collection="度假系列",
        price_cents=10999,
        image_url="/catalogue-products/women-bamboo-moon-tshirt.png",
        sizes=["S", "M", "L", "XL"],
        colors=["#000000"],
        in_stock=True,
    ),
    _product(
        sku="WOMEN-007",
        slug="women-mountain-rust-tshirt",
        name="山月鹿影宽松T恤",
        category="女装",
        product_type="T恤",
        collection="春夏精选",
        price_cents=10999,
        image_url="/catalogue-products/women-mountain-rust-tshirt.png",
        sizes=["S", "M", "L", "XL"],
        colors=["#89541f"],
        in_stock=True,
    ),
    _product(
        sku="WOMEN-008",
        slug="women-plantable-dress",
        name="种子吊牌连衣裙",
        category="女装",
        product_type="连衣裙",
        collection="春夏精选",
        price_cents=15999,
        image_url="/catalogue-products/women-plantable-dress.png",
        sizes=["S", "M", "L"],
        colors=["#dec78f", "#ffffff"],
        in_stock=True,
    ),
    _product(
        sku="WOMEN-009",
        slug="women-plantable-cardigan",
        name="植物吊牌针织开衫",
        category="女装",
        product_type="针织衫",
        collection="轻通勤",
        price_cents=14999,
        image_url="/catalogue-products/women-plantable-cardigan.png",
        sizes=["S", "M", "L", "XL"],
        colors=["#dec78f"],
        in_stock=True,
    ),
    _product(
        sku="GEAR-001",
        slug="gear-backpack",
        name="轻量徒步背包",
        category="装备",
        product_type="背包",
        collection="轻量出行",
        price_cents=19999,
        old_price_cents=23999,
        image_url="/catalogue-products/gear-backpack.png",
        sizes=[],
        colors=["#000000", "#89541f", "#dec78f", "#808080", "#ffffff", "#0b7fb8"],
        requires_size=False,
        in_stock=True,
        stock_total=18,
    ),
    _product(
        sku="GEAR-002",
        slug="gear-bottle",
        name="保温旅行水壶",
        category="装备",
        product_type="水壶",
        collection="户外基础",
        price_cents=6999,
        image_url="/catalogue-products/gear-bottle.png",
        sizes=[],
        colors=["#000000", "#89541f", "#dec78f", "#808080", "#ffffff", "#0b7fb8"],
        requires_size=False,
        in_stock=True,
        stock_total=30,
    ),
    _product(
        sku="GEAR-003",
        slug="gear-tent",
        name="双人轻便帐篷",
        category="装备",
        product_type="帐篷",
        collection="露营精选",
        price_cents=39999,
        image_url="/catalogue-products/gear-tent.png",
        sizes=[],
        colors=["#000000", "#89541f", "#dec78f", "#808080", "#ffffff", "#0b7fb8"],
        requires_size=False,
        in_stock=False,
        stock_total=0,
    ),
    _product(
        sku="GEAR-004",
        slug="gear-poles",
        name="折叠登山杖",
        category="装备",
        product_type="登山杖",
        collection="户外基础",
        price_cents=11999,
        image_url="/catalogue-products/gear-poles.png",
        sizes=[],
        colors=["#000000", "#89541f", "#dec78f", "#808080", "#ffffff", "#0b7fb8"],
        requires_size=False,
        in_stock=True,
    ),
    _product(
        sku="MERCH-001",
        slug="merch-badges",
        name="城市旅行徽章组",
        category="创意周边",
        product_type="徽章",
        collection="城市纪念",
        price_cents=2999,
        old_price_cents=3999,
        image_url="/catalogue-products/merch-badges.png",
        sizes=[],
        colors=["#000000", "#89541f", "#dec78f", "#808080", "#ffffff", "#0b7fb8"],
        requires_size=False,
        in_stock=True,
        stock_total=60,
    ),
    _product(
        sku="MERCH-002",
        slug="merch-stickers",
        name="目的地贴纸包",
        category="创意周边",
        product_type="贴纸",
        collection="旅行手账",
        price_cents=1999,
        image_url="/catalogue-products/merch-stickers.png",
        sizes=[],
        colors=["#000000", "#89541f", "#dec78f", "#808080", "#ffffff", "#0b7fb8"],
        requires_size=False,
        in_stock=True,
        stock_total=80,
    ),
    _product(
        sku="MERCH-003",
        slug="merch-tote",
        name="路线帆布袋",
        category="创意周边",
        product_type="帆布袋",
        collection="限定插画",
        price_cents=4999,
        image_url="/catalogue-products/merch-tote.png",
        sizes=[],
        colors=["#000000", "#89541f", "#dec78f", "#808080", "#ffffff", "#0b7fb8"],
        requires_size=False,
        in_stock=False,
        stock_total=0,
    ),
    _product(
        sku="MERCH-004",
        slug="merch-postcards",
        name="风景明信片套装",
        category="创意周边",
        product_type="明信片",
        collection="旅行手账",
        price_cents=2499,
        image_url="/catalogue-products/merch-postcards.png",
        sizes=["S", "M", "L", "XL", "XXL"],
        colors=["#000000", "#89541f", "#dec78f", "#808080", "#ffffff", "#0b7fb8"],
        in_stock=True,
        stock_total=55,
    ),
]
