-- Profiles Table (Extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  avatar_url text,
  bio text,
  role text not null default 'user',
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to automatically create profile
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Posts Table
create table public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  content text,
  type text check (type in ('video', 'image', 'article')) not null,
  media_urls text[] default '{}',
  status text check (status in ('published', 'draft')) default 'published',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Comments Table (Supports threading)
create table public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  parent_id bigint references public.comments(id) on delete cascade,
  content text not null,
  is_deleted boolean not null default false,
  deleted_at timestamp with time zone,
  deleted_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.comments enable row level security;
create policy "Comments are viewable by everyone." on public.comments for select using (coalesce(is_deleted, false) = false);

-- Messages Table (Private Chat)
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  receiver_id uuid references public.profiles(id) on delete cascade not null,
  content text,
  media_url text,
  type text check (type in ('text', 'image', 'video')) default 'text',
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Interactions Table (For Recommendations)
create table public.interactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  type text check (type in ('like', 'collect', 'share', 'view')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id, type)
);

-- Storage Buckets Setup (Execute via SQL Editor or Dashboard)
-- insert into storage.buckets (id, name) values ('media', 'media');

-- RLS Policies (Examples)
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id and coalesce(role, 'user') = 'user');
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create or replace function public.prevent_profile_role_self_update()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() = new.id and new.role is distinct from old.role then
    raise exception 'profile role cannot be changed by the profile owner';
  end if;

  return new;
end;
$$;

create trigger prevent_profile_role_self_update
before update of role on public.profiles
for each row execute function public.prevent_profile_role_self_update();

revoke execute on function public.prevent_profile_role_self_update() from anon, authenticated;

alter table public.posts enable row level security;
create policy "Posts are viewable by everyone." on public.posts for select using (true);

alter table public.messages enable row level security;
create policy "Users can view their own messages." on public.messages for select using (auth.uid() = sender_id or auth.uid() = receiver_id);
create policy "Users can insert messages." on public.messages for insert with check (auth.uid() = sender_id);
