# Generated by Django 6.0.3 on 2026-03-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Knowledge Base Entry",
                "verbose_name_plural": "Knowledge Base Entries",
                "db_table": "knowledge_base",
                "managed": True,
            },
        ),
    ]
