# Generated by Django 6.0.3 on 2026-03-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalCompleteDataset",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("city", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
                ("star_rating", models.CharField(max_length=255)),
                ("score", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("sales_volume", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("is_free", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("longitude", models.CharField(max_length=255)),
                ("latitude", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("keywords", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "final_complete_dataset",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TravelScraperSight",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("introduce", models.TextField()),
                ("score", models.CharField(max_length=20)),
                ("position", models.CharField(max_length=255)),
                ("grade", models.CharField(max_length=100)),
                ("images", models.TextField()),
                ("comments", models.TextField()),
                ("url", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("city_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "travel_scraper_sight",
                "managed": False,
            },
        ),
    ]
