# Generated by Django 6.0.3 on 2026-04-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0005_admin_qatest_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminqatestmessage",
            options={"managed": True, "ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="adminqatestsession",
            options={"managed": True, "ordering": ["-updated_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="embeddingprofile",
            options={
                "managed": True,
                "verbose_name": "Embedding 配置",
                "verbose_name_plural": "Embedding 配置列表",
            },
        ),
        migrations.AlterModelOptions(
            name="knowledgebase",
            options={
                "managed": True,
                "ordering": ["-updated_at"],
                "verbose_name": "知识库条目",
                "verbose_name_plural": "知识库条目列表",
            },
        ),
        migrations.AlterField(
            model_name="embeddingprofile",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
