# Generated by Django 6.0.3 on 2026-04-02 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0006_alter_adminqatestmessage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgebase",
            options={
                "managed": True,
                "ordering": ["-updated_at"],
                "verbose_name": "?????",
                "verbose_name_plural": "???????",
            },
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="kind",
            field=models.CharField(
                choices=[("knowledge_base", "???"), ("document", "??")],
                db_index=True,
                default="document",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="parent_knowledge_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_documents",
                to="data_engine.knowledgebase",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "???"),
                    ("active", "???"),
                    ("rejected", "???"),
                    ("archived", "???"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
