# Generated by Django 5.2 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0007_alter_knowledgebase_options_knowledgebase_kind_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelBookingIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("trip_name", models.CharField(blank=True, default="", max_length=200)),
                ("contact_name", models.CharField(blank=True, default="", max_length=100)),
                ("contact_phone", models.CharField(blank=True, default="", max_length=40)),
                ("note", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("reviewed", "Reviewed"), ("contacted", "Contacted"), ("archived", "Archived")], default="pending", max_length=20)),
                ("total_estimated_cost", models.FloatField(default=0)),
                ("items", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "travel_booking_intent",
                "managed": True,
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TravelDiscoverySignal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("spot_key", models.CharField(db_index=True, max_length=120)),
                ("signal_type", models.CharField(choices=[("view", "View"), ("itinerary_add", "Itinerary Add"), ("booking_intent", "Booking Intent")], max_length=30)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "travel_discovery_signal",
                "managed": True,
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TravelItineraryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("spot_key", models.CharField(max_length=120)),
                ("spot_name", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=255)),
                ("price", models.FloatField(default=0)),
                ("rating", models.FloatField(default=0)),
                ("cover_image", models.TextField(blank=True, default="")),
                ("recommendation_reason", models.CharField(blank=True, default="", max_length=255)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("spot_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "travel_itinerary_item",
                "managed": True,
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="travelitineraryitem",
            constraint=models.UniqueConstraint(fields=("user_id", "spot_key"), name="unique_itinerary_spot_per_user"),
        ),
    ]
