# Generated by Django 5.2 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0008_traveldiscovery_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="kind",
            field=models.CharField(
                choices=[
                    ("knowledge_base", "???"),
                    ("dataset", "???"),
                    ("document", "??"),
                ],
                db_index=True,
                default="document",
                max_length=20,
            ),
        ),
    ]
