# Generated by Codex on 2026-05-05

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0009_alter_knowledgebase_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=80)),
                ("image_url", models.TextField(blank=True, default="")),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="CNY", max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                ("stock_total", models.PositiveIntegerField(default=0)),
                ("stock_reserved", models.PositiveIntegerField(default=0)),
                ("stock_sold", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products",
                "managed": True,
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("product_snapshot", models.JSONField(blank=True, default=dict)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price_cents", models.PositiveIntegerField(default=0)),
                ("total_amount_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="CNY", max_length=8)),
                ("status", models.CharField(choices=[("pending_payment", "Pending Payment"), ("payment_created", "Payment Created"), ("paid", "Paid"), ("payment_failed", "Payment Failed"), ("canceled", "Canceled")], db_index=True, default="pending_payment", max_length=24)),
                ("payment_provider", models.CharField(default="zpay", max_length=24)),
                ("payment_type", models.CharField(choices=[("alipay", "Alipay"), ("wxpay", "WeChat Pay")], default="alipay", max_length=16)),
                ("out_trade_no", models.CharField(db_index=True, max_length=32, unique=True)),
                ("zpay_trade_no", models.CharField(blank=True, default="", max_length=80)),
                ("zpay_order_id", models.CharField(blank=True, default="", max_length=80)),
                ("pay_url", models.TextField(blank=True, default="")),
                ("client_request_id", models.CharField(blank=True, db_index=True, default="", max_length=80)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="data_engine.product")),
            ],
            options={
                "db_table": "payment_orders",
                "managed": True,
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(default="zpay", max_length=24)),
                ("event_type", models.CharField(default="notify", max_length=40)),
                ("signature_valid", models.BooleanField(default=False)),
                ("amount_matches", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="data_engine.paymentorder")),
            ],
            options={
                "db_table": "payment_events",
                "managed": True,
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="paymentorder",
            constraint=models.UniqueConstraint(condition=~Q(client_request_id=""), fields=("user_id", "client_request_id"), name="unique_payment_order_client_request_per_user"),
        ),
    ]
