# Generated by Codex on 2026-05-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0010_products_payment_orders"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommerceOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_no", models.CharField(db_index=True, max_length=32, unique=True)),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(choices=[("pending_payment", "Pending Payment"), ("payment_created", "Payment Created"), ("paid", "Paid"), ("payment_failed", "Payment Failed"), ("canceled", "Canceled")], db_index=True, default="pending_payment", max_length=24)),
                ("subtotal_cents", models.PositiveIntegerField(default=0)),
                ("shipping_cents", models.PositiveIntegerField(default=0)),
                ("discount_cents", models.PositiveIntegerField(default=0)),
                ("total_amount_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="CNY", max_length=8)),
                ("payment_method", models.CharField(choices=[("alipay", "Alipay")], default="alipay", max_length=16)),
                ("shipping_method", models.CharField(blank=True, default="standard", max_length=80)),
                ("shipping_address", models.JSONField(blank=True, default=dict)),
                ("contact_email", models.EmailField(blank=True, default="", max_length=254)),
                ("contact_phone", models.CharField(blank=True, default="", max_length=40)),
                ("note", models.TextField(blank=True, default="")),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "commerce_orders",
                "managed": True,
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CommerceOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_snapshot", models.JSONField(blank=True, default=dict)),
                ("sku", models.CharField(blank=True, default="", max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("image_url", models.TextField(blank=True, default="")),
                ("unit_price_cents", models.PositiveIntegerField(default=0)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("line_total_cents", models.PositiveIntegerField(default=0)),
                ("selected_size", models.CharField(blank=True, default="", max_length=40)),
                ("selected_color", models.CharField(blank=True, default="", max_length=80)),
                ("cart_item_id", models.CharField(blank=True, default="", max_length=160)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="data_engine.commerceorder")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="commerce_order_items", to="data_engine.product")),
            ],
            options={
                "db_table": "commerce_order_items",
                "managed": True,
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="commerce_order",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payments", to="data_engine.commerceorder"),
        ),
    ]
