# Generated by Codex on 2026-05-06

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def set_existing_expiration(apps, schema_editor):
    CommerceOrder = apps.get_model("data_engine", "CommerceOrder")
    PaymentOrder = apps.get_model("data_engine", "PaymentOrder")
    expires_at = timezone.now() + timedelta(minutes=3)
    CommerceOrder.objects.filter(status__in=["pending_payment", "payment_created"], expires_at__isnull=True).update(expires_at=expires_at)
    PaymentOrder.objects.filter(status__in=["pending_payment", "payment_created"], expires_at__isnull=True).update(expires_at=expires_at)


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0011_commerce_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="commerceorder",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="commerceorder",
            name="status",
            field=models.CharField(choices=[("pending_payment", "Pending Payment"), ("payment_created", "Payment Created"), ("paid", "Paid"), ("payment_failed", "Payment Failed"), ("canceled", "Canceled"), ("expired", "Expired")], db_index=True, default="pending_payment", max_length=24),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=models.CharField(choices=[("pending_payment", "Pending Payment"), ("payment_created", "Payment Created"), ("paid", "Paid"), ("payment_failed", "Payment Failed"), ("canceled", "Canceled"), ("expired", "Expired")], db_index=True, default="pending_payment", max_length=24),
        ),
        migrations.RunPython(set_existing_expiration, migrations.RunPython.noop),
    ]
