# Generated by Codex on 2026-05-09

from django.db import migrations


def keep_out_of_stock_products_visible(apps, schema_editor):
    Product = apps.get_model("data_engine", "Product")
    Product.objects.filter(is_active=False, stock_total=0).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0012_order_expiration"),
    ]

    operations = [
        migrations.RunPython(keep_out_of_stock_products_visible, migrations.RunPython.noop),
    ]
