# Generated by Django 6.0.3 on 2026-03-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="连接名称"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("postgresql", "PostgreSQL / Supabase"),
                            ("sqlite", "SQLite"),
                        ],
                        max_length=20,
                        verbose_name="数据库类型",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="主机地址"
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True, default=3306, null=True, verbose_name="端口"
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "password_encrypted",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="密码(加密)"
                    ),
                ),
                (
                    "database_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="数据库名"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="文件路径"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "数据源",
                "verbose_name_plural": "数据源管理",
            },
        ),
    ]
